services:
  namaz-app:
    container_name: namaz-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
        - NEXT_PUBLIC_GA4_ID=${NEXT_PUBLIC_GA4_ID}
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - main-network

networks:
  main-network:
    external: true