export { fetcher } from './fetcher'
export { selectCity } from './selectCity/selectCity'
export { percentageCounter } from './percentageCounter/percentageCounter'
export { pageview, GTM_ID } from './gtm'
// export { leapYearOffset } from './leapYearOffset/leapYearOffset'
// export { generateDates } from './generateToDates/generateDates'
// export { runMiddleware } from './cors/cors'
