name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  TARGET_DIRECTORY: ${{ secrets.TARGET_DIRECTORY }}

  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ vars.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
  NEXT_PUBLIC_GTM_ID: ${{ vars.NEXT_PUBLIC_GTM_ID }}
  NEXT_PUBLIC_GA4_ID: ${{ vars.NEXT_PUBLIC_GA4_ID }}
  NEXT_PUBLIC_HIJRI_OFFSET: ${{ vars.NEXT_PUBLIC_HIJRI_OFFSET }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Build with Next.js
        run: pnpm next build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: next-build
          path: ./.next

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: next-build
          path: ./.next

      - name: Upload to Ubuntu server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          source: ./*
          target: ${{ env.TARGET_DIRECTORY }}

      - name: Execute deployment commands on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.TARGET_DIRECTORY }}
            git fetch
            git pull
            pnpm install
            pm2 restart nam.az
            echo "Files uploaded successfully!"
