name: Staging Release

on:
  workflow_dispatch:

jobs:
  build-and-version-minor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Version Minor
      id: pnpm_version
      run: |
        NEW_VERSION=$(pnpm version minor -m "Staging v%s")
        echo "New Version: $NEW_VERSION"
        echo "::set-output name=version::$NEW_VERSION"

    - name: Push Changes
      run: git push origin HEAD:main --follow-tags