name: Staging Release

on:
  workflow_dispatch:

jobs:
  build-and-version-minor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Version Minor
      id: pnpm_version
      run: |
        NEW_VERSION=$(pnpm version minor -m "Staging v%s" --no-git-tag-version)
        echo "New Version: $NEW_VERSION"
        echo "::set-output name=version::$NEW_VERSION"

    - name: Create and Push Tag
      run: |
        git tag "${{ steps.pnpm_version.outputs.version }}"
        git push origin "${{ steps.pnpm_version.outputs.version }}"