name: CI/CD Main Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Version Patch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        npm version patch
        git push origin HEAD:main