name: CI/CD Main Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Version Patch
      id: pnpm_version
      run: |
        NEW_VERSION=$(pnpm version patch --no-git-tag-version)
        echo "::set-output name=version::$NEW_VERSION"

    - name: Commit and Push Changes
      run: |
        git add -A
        git commit -m "${{ steps.pnpm_version.outputs.version }}"
        git push origin HEAD:main